version: '3.9'

services:
    node1:
      image: cassandra:4.0
      ports:
        - 9142:9042
      volumes:
        - cassandra1:/var/lib/cassandra
      env_file:
        - cassandra.env
#      environment:

    node2:
      image: cassandra:4.0
      ports:
        - 9242:9042
      volumes:
        - cassandra2:/var/lib/cassandra
      env_file:
        - cassandra.env
      depends_on:
        - node1

    node3:
      image: cassandra:4.0
      ports:
        - 9342:9042
      volumes:
        - cassandra3:/var/lib/cassandra
      env_file:
        - cassandra.env
#      environment:
      depends_on:
        - node2

    node4:
      image: cassandra:4.0
      ports:
        - 9442:9042
      volumes:
        - cassandra4:/var/lib/cassandra
      env_file:
        - cassandra.env
#      environment:
      depends_on:
        - node3

volumes:
  cassandra1:
  cassandra2:
  cassandra3:
  cassandra4: